// Generated by CoffeeScript 1.4.0

buster.testCase("hoge", {
  "test hogehoge": function() {
    /*:DOC += <div id="hogehoge">aaaa</div>
    */
    console.log(document.body.innerHTML);
    assert(document.getElementById('hogehoge').innerHTML === "aaaa");
    console.log(document.getElementById('hogehoge').innerHTML);
  }
});
